baseURL = "https://keen-leakey-dd5285.netlify.app/"
languageCode = "en-us"
theme = "raditian-free-hugo-theme"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]


  [[menu.header]]
  name = "Sponsor"
  URL = "#sponsors"
  weight = 1

  [[menu.header]]
  name = "Tickets"
  URL = "#tickets"
  weight = 2
  
  [[menu.header]]
  name = "Schedule"
  URL = "#schedule"
  weight = 3

  [[menu.header]]
  name = "Menu"
  URL = "#menu"
  weight = 4

  [[menu.header]]
  name = "Directions"
  URL = "#directions"
  weight = 5
  
  [[menu.header]]
  name = "Explore SCV"
  URL = "#explore"
  weight = 6

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 7


  [[menu.footer]]
  name = "Volunteer"
  URL = "#volunteer"
  weight = 1

  [[menu.footer]]
  name = "Tickets"
  URL = "#tickets"
  weight = 2
  
  [[menu.footer]]
  name = "Schedule"
  URL = "#schedule"
  weight = 3

  [[menu.footer]]
  name = "Menu"
  URL = "#menu"
  weight = 4

  [[menu.footer]]
  name = "Directions"
  URL = "#directions"
  weight = 5

  [[menu.footer]]
  name = "Explore SCV"
  URL = "#explore"
  weight = 6

  [[menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 6

  


[params]

  sections = ["showcase", "sponsors", "tickets", "schedule", "menu", "directions", "explore", "contact"]

  [params.footer]
      copyright = "©2021 All rights reserved | Pride of the Vikings."